### ISSUE TITLE
url() path separator should be system agnostic

### ISSUE THREAD

**Issue by soubok** [shutterstock/postcss-copy-assets#5]
Hello,
on windows, the following url() path:
`url("../src/components/bootstrap/fonts/glyphicons-halflings-regular.eot")`
is transformed into:
`url("src\components\bootstrap\fonts\glyphicons-halflings-regular.eot")`
this is not expected.

**Comment by FranckFreiburger** [comment]
thanks

**Comment by alexmchardy** [comment]
Fixed in #9
