### ISSUE TITLE
Paths should always have the format url(../folder1/folder2)

### ISSUE THREAD

**Issue by 0xclx** [shutterstock/postcss-copy-assets#7]
Hello!

I have encountered a mission critical error with your PostCSS Plugin.
Because of your use of path.relative, the path that results from your plugin in my css-files under windows is something like: url('folder1\folder2') which is not allowed, neither working in CSS-Files. The correct syntax, under any circumstance, would be: url('folder1/folder2')

I hope that you can reproduce this, and to hear a reponse from you.

**Comment by alexmchardy** [comment]
At first glance it looks like we should use `path.posix` to correct this issue. I'll work on getting a Windows environment to test in so I can patch this ASAP.

**Comment by alexmchardy** [comment]
@Z3roCoder please test out the fix in #9 if you are able.

**Comment by alexmchardy** [comment]
Fixed in #9

**Comment by 0xclx** [comment]
Could this please be pushed to NPM?
Trying to use the plugin resulted in the exact same error like I reported.
